### PR TITLE
fix(linting): shorten long lines

### PR DESCRIPTION
**Pull request by tommorris**
# Description

Shorten line lengths the linter is complaining about.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have run `yarn test` to make sure my changes pass all linters
- [x] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

### CODE REVIEW

**Review by cbetta — APPROVED** [review]

**Comment by gryevns** [comment]
Can we add a linter to do this going forwards?

**Comment by tommorris** [comment]
@gryevns there is a linter. It's not tied into CI because there's a bunch of linting errors (because it's not tied into CI, because there's a bunch of linting errors, `InternalError: too much recursion` etc.)

**Comment by gryevns** [comment]
> @gryevns there is a linter. It's not tied into CI because there's a bunch of linting errors (because it's not tied into CI, because there's a bunch of linting errors, `InternalError: too much recursion` etc.)

Thinking more like a pre-commit check and/or prettier (or similar) to format files on save locally.

**Comment by tommorris** [comment]
The `package.json` assumes yamllint is installed. yamllint doesn't have autoformatting. Could use something like Google's go-based [yamlfmt](https://github.com/google/yamlfmt) instead. Will file a JIRA though.

**Comment by gryevns** [comment]
This should be redundant with https://github.com/gr4vy/gr4vy-openapi/pull/305 merged.

**Pull request closed without merging**
