### PR TITLE
chore: deprecate payment service position

### PR DESCRIPTION
**Pull request by gryevns**
# Description

https://gr4vy.atlassian.net/browse/TA-2590

* Removes card rule resources (removed from api)
* Adds deprecation boolean to position field for payment service resource

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own changes
- [ ] I have run `yarn test` to make sure my changes pass all linters
- [ ] I have pulled the latest changes from the upstream `main` branch

## Contribution guidelines

For contribution guidelines, styleguide, and other helpful information please
see the `CONTRIBUTING.md` file in the root of this project.

### CODE REVIEW

**Comment by gryevns** [comment]
@cbetta is this a valid path towards removing `position` from the payment services resource in core-api?

**Comment by cbetta** [comment]
@gryevns yes I think we can safely remove it. Would not really affect the SDKs.

**Comment by cbetta** [comment]
@gryevns shall we just remove this feature from the API spec instead completely and merge this? I can do this if you're OK with it.

**Comment by gryevns** [comment]
> @gryevns shall we just remove this feature from the API spec instead completely and merge this? I can do this if you're OK with it.

Yes please.

**Review by cbetta — APPROVED** [review]

**Pull request merged**
